:Author: biospherexx
:Email: natashablong@gmail.com
:Date: 13/08/2020
:Revision: 1

= Project: Universal Flex Fuel Translator

How to use an Arduino Nano to translate the Hz output of a Continental Flex Fuel Sensor to a Analog Voltage output (using Pulse Width Modulation).
An aftermarket Translator can easily cost $500, but with an Arduino Nano you can make one for $20.

== Installation
Navigate to the How To Guide for instructions on building your own Flex Fuel Sensor Translator:
https://github.com/NatashaBlong/Universal-Flex-Fuel-Translator/blob/main/A%20How%20To%20Guide.pdf

== Credits:

Check out the FreqMeasure Library, created by Paul Stoffregen, and used in this project -> https://www.arduinolibraries.info/libraries/freq-measure

== Resources for Future Updates:
Serial Information for BlueTooth (not yet tested) -> https://www.arduino.cc/reference/en/language/functions/communication/serial/

The Continental Ethanol Content Sensor also outputs the fuel temperature through a 1-5 millisecond pulsewidth (-40 - 125 C) -> https://www.bmotorsports.com/shop/product_info.php/xrf/gshp/products_id/3408

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── Flex_Fuel_Translator.ino                               => main Arduino file 
  ├── Flex Fuel Translator Schematic (Arduino Nano).png      => schematic
  ├── A How To Guide.pdf                                     => A How to Guide
  └── ReadMe.adoc                                            => this file
....

=== Contributing
To contribute to this project please contact biospherexx https://id.arduino.cc/biospherexx

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name       | Part number       | Quantity
| R1 | 1.8k Resistor   | 	CF18JT1K80CT-ND  | 2
| L1 | 100uF Capacitor | 	P15369CT-ND      | 1
| A1 | Arduino Nano    | A000005           | 1
|===

=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
